[package]
name = "app"
version = "0.0.3"
authors = ["very1fake <very1fake.coder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.3", default-features = false, features = ["debug", "tokio", "glow"] }
iced_native = "0.4"
tokio = { version = "1.6", features = ["time"] }
